export const CONTAINER_PADDING = 16;
export const THUMBNAIL_SIZE = 48;
export const THUMBNAIL_RIGHT_MARGIN = 16;
export const TEXT_STARTS_AT =
    CONTAINER_PADDING + THUMBNAIL_SIZE + THUMBNAIL_RIGHT_MARGIN;
